### PR TITLE
Rebrand as Raku

### PR DESCRIPTION
**Pull request by hankache**

### CODE REVIEW

**Comment by AlexDaniel** [comment]
Can you do more changes? For example, right in the same file it links to perl6.org which is now raku.org.

**Comment by hankache** [comment]
@AlexDaniel Sure. 
What about docs? Should I change to docs.raku.org?
I've been wanting to do so for a while, but can't figure out why raku.org still links docs.perl6.org

**Comment by AlexDaniel** [comment]
Because when changes to raku.org were being made there was no docs.raku.org. Just change anything you notice, including links on raku.org :)

**Comment by hankache** [comment]
Will do :)

**Comment by AlexDaniel** [comment]
Thanks!

**Pull request merged**
